### ISSUE TITLE
No safari

### ISSUE THREAD

**Issue by tobiasbed** [HonbraDev/assignmentsplus#1]
I want safari. Implement support for safari. pls

**Comment by HonbraDev** [comment]
I want console. Send console. pls

**Comment by tobiasbed** [comment]
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/84775852/165748198-096b3a1f-857e-4f01-9061-f5718ff9b25e.png">

Here is console. Fix console. pls

**Comment by HonbraDev** [comment]
Fixed by #2.

**Comment by tobiasbed** [comment]
yay
